import logging
import random
import requests
import urllib.parse

logger = logging.getLogger(__name__)

POLLINATIONS_IMAGE = "https://image.pollinations.ai/prompt/{}?seed={}&width=1024"
POLLINATIONS_TEXT = "https://text.pollinations.ai/prompt/{}"

TOPICS = [
    "fantasy landscape", "cyberpunk city", "cute animal", "futuristic vehicle",
    "underwater scene", "space exploration", "steampunk machine", "magical forest",
    "desert ruins", "neon portrait", "floating islands", "mechanical dragon",
    "aurora sky", "cherry blossom", "volcanic forge", "ice palace",
    "clockwork garden", "quantum realm", "alien planet", "ancient civilization"
]

def generate_prompt():
    try:
        topic = random.choice(TOPICS)
        seed = random.randint(0, 999999)
        prompt = f"Single creative AI art prompt about {topic} (max 15 words, scene+style). Seed:{seed}. Return ONLY the prompt."
        url = POLLINATIONS_TEXT.format(urllib.parse.quote(prompt))
        resp = requests.get(url, timeout=30)
        resp.raise_for_status()
        text = resp.text.strip().strip('"\'').splitlines()[0][:120]
        logger.info(f"AI prompt: {text}")
        return text
    except Exception as e:
        logger.error(f"Prompt generation failed: {e}")
        return random.choice(TOPICS) + ", digital art"

def generate_image(prompt, output_path):
    try:
        seed = random.randint(0, 999999)
        url = POLLINATIONS_IMAGE.format(urllib.parse.quote(prompt), seed)
        logger.info(f"Generating image: {prompt[:80]}...")
        resp = requests.get(url, timeout=120)
        resp.raise_for_status()
        with open(output_path, "wb") as f:
            f.write(resp.content)
        logger.info(f"Image saved ({len(resp.content)} bytes)")
        return True
    except Exception as e:
        logger.error(f"Image generation failed: {e}")
        return False

def generate_caption(image_prompt):
    try:
        prompt = f"Write one short poetic French Facebook caption (1 sentence) for: {image_prompt}. Return ONLY the caption."
        url = POLLINATIONS_TEXT.format(urllib.parse.quote(prompt))
        logger.info("Generating caption...")
        resp = requests.get(url, timeout=30)
        resp.raise_for_status()
        caption = resp.text.strip().splitlines()[0][:200]
        logger.info(f"Caption: {caption}")
        return caption
    except Exception as e:
        logger.error(f"Caption generation failed: {e}")
        return "Generated by AI"