from instagrapi import Client
import os
import logging
from dotenv import load_dotenv
from instagrapi.exceptions import ClientError, ChallengeRequired, TwoFactorRequired, BadPassword, PleaseWaitFewMinutes

load_dotenv()
logger = logging.getLogger(__name__)

def post_to_instagram(image_path, caption):
    username = os.getenv("INSTA_USERNAME")
    password = os.getenv("INSTA_PASSWORD")

    if not username or not password:
        logger.error("Instagram credentials not found in environment variables.")
        return False

    cl = Client()
    session_file = "session.json"

    # Load settings if they exist
    if os.path.exists(session_file):
        cl.load_settings(session_file)

    try:
        # Use relogin=True to handle session expiration gracefully
        cl.login(username, password, relogin=True)

        # Save settings for next time
        cl.dump_settings(session_file)

        # Attempt to upload
        cl.photo_upload(image_path, caption)
        logger.info("Posted successfully!")
        return True
    except ChallengeRequired:
        logger.error("Instagram login failed: Challenge Required. Please complete the challenge manually.")
        return False
    except TwoFactorRequired:
        logger.error("Instagram login failed: Two-Factor Authentication Required. Please handle 2FA manually.")
        return False
    except BadPassword:
        logger.error("Instagram login failed: Invalid username or password.")
        return False
    except PleaseWaitFewMinutes:
        logger.error("Instagram action failed: Please wait a few minutes before trying again (rate limit).")
        return False
    except ClientError as e:
        logger.error(f"An Instagram client error occurred: {e}")
        return False
    except Exception as e:
        logger.error(f"An unexpected error occurred while posting to Instagram: {e}")
        return False
if __name__ == "__main__":
    # Example usage
    # post_to_instagram("output.png", "Generated by AI!")
    pass
